name: Random Number Update

on:
  schedule:
    - cron: '*/1 * * * *'  # Executa a cada 1 minuto
  workflow_dispatch:  # Permite execução manual

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Gerar número aleatório e atualizar o JSON
        run: |
          # Gera um número aleatório entre 5 e 50
          RANDOM_NUMBER=$((RANDOM % 46 + 5))

          # Gera o timestamp atual
          TIMESTAMP=$(date +%s)
          
          # Cria ou atualiza o arquivo JSON
          FILE="data.json"

          # Verifica se o arquivo já existe
          if [ ! -f $FILE ]; then
            echo '{"current": {}, "old": []}' > $FILE
          fi

          # Lê o conteúdo atual do JSON
          CURRENT_NUMBER=$(jq '.current.number' $FILE)

          # Se já existir um número atual, move ele para "old"
          if [ "$CURRENT_NUMBER" != "null" ]; then
            # Adiciona o número atual à lista "old" com timestamp
            jq ".old += [{\"number\": $CURRENT_NUMBER, \"timestamp\": $TIMESTAMP}]" $FILE > temp.json && mv temp.json $FILE
          fi

          # Atualiza o "current" com o novo número e timestamp
          jq ".current = {\"number\": $RANDOM_NUMBER, \"timestamp\": $TIMESTAMP}" $FILE > temp.json && mv temp.json $FILE

          # Imprime o conteúdo atualizado do JSON para depuração
          cat $FILE

      - name: Commit e push do arquivo atualizado
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Adicionando novo número aleatório ao JSON com timestamp'
