name: Update Timestamp JSON
on:
  workflow_dispatch:  # Permite rodar manualmente no GitHub
  schedule:
    - cron: "*/1 * * * *"  # Atualiza a cada 5 minutos

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp.json
        run: |
          TIMESTAMP=$(date +%s)
          DECIMAL=$(echo "scale=1; $TIMESTAMP / 1000 - $TIMESTAMP / 1000" | bc)
          echo "{ \"timestamp\": \"$TIMESTAMP\", \"decimal\": \"$DECIMAL\" }" > timestamp.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add timestamp.json
          git commit -m "Update timestamp"
          git push
